config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :users, only: [:show, :index]
  resources :reports, only: [:create, :destroy, :show]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'users/:id/following' => 'relationships#following', as: 'following'
  get 'users/:id/follower' => 'relationships#follower', as: 'follower'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :Reports, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  validates :name, presence: true, uniqueness: true

  validate :validate_avatar

  def validate_avatar
    return unless avatar.attached?
    if avatar.blob.byte_size > 5.megabytes
      avatar.purge
    elsif !image?
      avatar.purge
    end
  end

  def image?
    %w[image/jpg image/jpeg image/gif image/png].include?(avatar.blob.content_type)
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  def after_account_update_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def following
    @user = User.find(params[:id])
    @reports = Report.where(reportee_id: @user.id)
  end

  def follower
    @user = User.find(params[:id])
    @reports = Report.where(reportee_id: @user.id)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def create
    report = Report.new(report_params)
    report.user_id = current_user.id
    report.save
    UserMailer.report_email(report).deliver
    redirect_back(fallback_location: root_path)
  end

  def destroy
    report = Report.find(params[:id])
    if params[:message].present?
      message = params[:message]
    else
      massage = "なし"
    end
    report.destroy
    if current_user.id != report.user_id
      UserMailer.reflection_email(report, message).deliver
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def report_params
    params.require(:report).permit(:title, :body, :reportee_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:name].present?
      @users = User.where('name LIKE ?', "%#{params[:name]}%")
    else
      @users = User.none
    end
    @reports = Report.where(reportee_id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @report = Report.new
    @reports = Report.where(reportee_id: @user.id)
  end

  # def edit
  #   @user = User.find(params[:id])
  #   if current_user != @user
  #     redirect_to edit_user_path(current_user.id)
  #   end
  # end

  # def update
  #   @user = User.find(params[:id])
  #   @user.update(user_params)
  #   redirect_to user_path(@user.id)
  # end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto text-center">
      <h1 class="mb-5 heading text-center">YOU HAVE BEEN REPORTED!!</h1>
      <p class="mb-5 px-3">
        このWEBアプリは、よくネットサービスなどにみられる「通報」という機能を現実世界に実装するサービスです。<br>
        <br>
        もしあなたが無礼を働かれたなら、このアプリを利用して匿名で相手を通報しましょう。<br>
        <br>
        もしあなたが無礼を働いたのなら、届いた通報を真摯に受け止めて反省しましょう。<br>
      </p>
      <div class="text-center">
        <% if !user_signed_in? %>
          <%= link_to "サインアップ", new_user_registration_path, class: "btn btn-info btn-lg" %>
          <%= link_to "サインイン", new_user_session_path, class: "btn btn-success btn-lg" %>
        <% else %>
          <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-info btn-lg" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_user_info.html.erb
<div class="row mb-3 pb-4 border-bottom border-dark">
    <div class="col-md-4">
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar.variant(resize_to_fill: [200, 200]), class: "rounded-circle mx-auto d-block" %>
      <% else %>
        <%= image_tag 'no_image.png', size: "200x200", class: "rounded-circle mx-auto d-block" %>
      <% end %>
    </div>
    <div class="col-md-8 p-5">
      <div>
        <h1><%= user.name %></h1>
        <p>
          <%= link_to following_path(user.id), class: "text-secondary" do %>Following <%= user.follower.count %><% end %>
           / 
          <%= link_to follower_path(user.id), class: "text-secondary" do %>Follower <%= user.followed.count %><% end %>
           /
          <%= link_to user_path(user.id), class: "text-secondary" do %>Reported <%= reports.where(reportee_id: user.id).count %><% end %>
        </p>
        <% if current_user == user %>
          <%= link_to "Edit Profile", edit_user_registration_path(user.id) %>
        <% else %>
          <% if current_user.following?(user) %>
            <%= link_to " フォロー中 ", unfollow_path(user.id), method: :POST, class: "btn btn-info btn-sm" %>
          <% else %>
            <%= link_to "フォローする", follow_path(user.id), method: :POST, class: "btn btn-outline-info btn-sm" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/_user_list.html.erb
  <div class="border row p-2 shadow m-4 p-3 border border-dark rounded text-center">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <%= link_to user_path(user.id) do %>
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar.variant(resize_to_fill: [50, 50]), class: "rounded-circle" %>
        <% else %>
          <%= image_tag 'no_image.png', size: "50x50", class: "rounded-circle" %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-4 my-auto">
      <%= link_to user_path(user.id), class: "text-dark" do %>
        <%= user.name %>
      <% end %>
    </div>
    <div class="col-md-3 my-auto">
      <% if current_user != user %>
        <% if current_user.following?(user) %>
          <%= link_to " フォロー中 ", unfollow_path(user.id), method: :POST, class: "btn btn-info btn-sm" %>
        <% else %>
          <%= link_to "フォローする", follow_path(user.id), method: :POST, class: "btn btn-outline-info btn-sm" %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Yhbr</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="apple-touch-icon" href="app/assets/images/icon.png">
    <link rel="android-touch-icon" href="app/assets/images/icon.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="nav-bar bg-danger mb-5">
        <div class="container">
            <%= link_to root_path do %>
              <%= image_tag('logo.png') %>
            <% end %>
        </div>
      </nav>
    </header>
    <% if user_signed_in? %>
      <div id="sp-menu">
        <h2 class="text-center border-bottom border-light">MENU</h2>
        <ul>
          <li><%= link_to "MyPage", user_path(current_user.id) %></li>
          <li><%= link_to "Search", users_path %></li>
          <li><%= link_to "Following", following_path(current_user.id) %></li>
          <li><%= link_to "Follower", follower_path(current_user.id) %></li>
          <li><%= link_to "EditProfile", edit_user_registration_path(current_user.id) %></li>
          <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    <% end %>

    <%= yield %>
    <footer>
      <div class="bg-danger mt-5 copyright">
        <div class="text-center text-white">
          <p>©︎CopyRight Ogikun</p>
        </div>
      </div>
    </footer>
    <%= javascript_pack_tag 'menu.js' %>
  </body>
</html>

app/views/relationships/follower.html.erb
<div class="container">
  <h2 class="text-center">Follower</h2>
  <% if @user.follower_user.count > 0 %>
    <% @user.follower_user.each do |user| %>
      <%= render "layouts/user_list", user: user%>
    <% end %>
  <% else %>
    <h4 class="text-center my-4 text-secondary">現在フォロワーがいません</h4>
  <% end %>
</div>

app/views/relationships/following.html.erb
<div class="container">
  <h2 class="text-center">Following</h2>
  <% if @user.following_user.count > 0 %>
    <% @user.following_user.each do |user| %>
      <%= render "layouts/user_list", user: user%>
    <% end %>
  <% else %>
    <h4 class="text-center my-4 text-secondary">誰もフォローしていません</h4>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="text-center">
    <h2>Search User</h2>
    <p>ユーザー名で知り合いを検索しましょう</p>
    <%= form_with url:users_path, method: :get, local: true do |f| %>
      <%= f.text_field :name %>
      <%= f.submit :Search %>
    <% end %>
  </div>
  <% @users.each do |user| %>
    <%= render "layouts/user_list", user: user%>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render "layouts/user_info", user: @user, reports: @reports%>
  <% if current_user == @user %>
    <h2 class="text-center">Reports</h2>
    <% if @reports.count < 1 %>
      <h4 class="text-center my-4 text-secondary">通報はありません</h4>
    <% else %>
      <% @reports.each do |report| %>
        <div class="shadow m-4 p-3 border border-dark rounded text-center">
          <h4>通報理由:</h4>
          <h3><%= report.title %></h3>
          <h5><%= report.body %></h5>
          <a href="#" class="btn btn-outline-danger btn-sm btn-block mt-4 col-6 mx-auto reflection">反省する</a>
          <div id="reflection-back" class="p-5">
              <div id="reflection-switch" class="reflection"></div>
              <div id="reflection-window" class="shadow mx-auto p-5 my-5 border border-dark rounded text-center text-dark bg-white col-md-8" >
                <h4>通報理由:</h4>
                <h3><%= report.title %></h3>
                <h5><%= report.body %></h5>
                <h5 class="mt-5 pt-5 border-top border-dark">Message</h5>
                <%= form_with url:report_path(report), method: :delete, local: true do |f| %>
                  <%= f.text_field :message, class: "col-12" %>
                  <%= f.submit :反省しました, class:"btn btn-success btn-sm mt-4 mx-auto col-7"%>
                <% end %>
              </div>
            </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="text-center">
      <% if @reports.where(user_id: current_user.id).count > 0 %>
        <h2>Your Reports</h2>
        <% @reports.where(user_id: current_user.id).each do |report| %>
          <div class="shadow m-4 p-3 border border-dark rounded text-center">
            <h4>通報理由:</h4>
            <h3><%= report.title %></h3>
            <h5><%= report.body %></h5>
            <%= link_to "取り消す", report_path(report), method: :delete, class:"btn btn-outline-danger btn-sm btn-block mt-4 col-6 mx-auto" %>
          </div>
        <% end %>
      <% end %>
      <h2>Report Form</h2>
      <%= form_with model: @report, local:true do |f| %>
        <div class="my-3">
          <label for="title">通報理由</label><br>
          <%= f.text_field :title, id:"title" %>
        </div>
        <div class="my-3">
          <label for="body">詳細内容</label><br>
          <%= f.text_area :body, id:"body" %>
        </div>
        <div class="mx-auto mt-5 col-6">
        <%= f.text_field :reportee_id, value: @user.id, class: "d-none"%>
        <%= f.submit '通報', class:"btn btn-danger btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'report.js'%>